name: 🧱 Setup Android Project (Fixed)

on:
  workflow_dispatch:

jobs:
  create-structure:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Android project structure
        run: |
          mkdir -p app/src/main/java/com/madhabam/passportstudio
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values

          echo 'rootProject.name = "PassportPhotoStudioApp"
include(":app")' > settings.gradle

          echo 'buildscript {
              repositories { google(); mavenCentral() }
              dependencies { classpath "com.android.tools.build:gradle:8.5.2" }
          }
          allprojects { repositories { google(); mavenCentral() } }
          task clean(type: Delete) { delete rootProject.buildDir }' > build.gradle

          echo 'plugins { id "com.android.application" }
          android {
              namespace "com.madhabam.passportstudio"
              compileSdk 34
              defaultConfig {
                  applicationId "com.madhabam.passportstudio"
                  minSdk 23
                  targetSdk 34
                  versionCode 1
                  versionName "1.0"
              }
              buildTypes { release { minifyEnabled false } }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
          }
          dependencies {
              implementation "androidx.appcompat:appcompat:1.7.0"
              implementation "com.google.android.material:material:1.12.0"
              implementation "androidx.constraintlayout:constraintlayout:2.2.0"
          }' > app/build.gradle

          echo '<?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.madhabam.passportstudio">
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:theme="@style/Theme.PassportPhotoStudio">
                  <activity android:name=".MainActivity">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>' > app/src/main/AndroidManifest.xml

          echo 'package com.madhabam.passportstudio;
          import androidx.appcompat.app.AppCompatActivity;
          import android.os.Bundle;
          import android.widget.TextView;
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  setContentView(R.layout.activity_main);
                  TextView text = findViewById(R.id.textView);
                  text.setText("📸 Passport Photo Studio Ready!");
              }
          }' > app/src/main/java/com/madhabam/passportstudio/MainActivity.java

          echo '<?xml version="1.0" encoding="utf-8"?>
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical"
              android:gravity="center">
              <TextView
                  android:id="@+id/textView"
                  android:text="Passport Photo Studio"
                  android:textSize="22sp"
                  android:textColor="#000"/>
          </LinearLayout>' > app/src/main/res/layout/activity_main.xml

          echo '<resources><string name="app_name">Passport Photo Studio</string></resources>' > app/src/main/res/values/strings.xml
          echo '<resources><style name="Theme.PassportPhotoStudio" parent="Theme.MaterialComponents.DayNight.NoActionBar"/></resources>' > app/src/main/res/values/themes.xml

          echo "✅ Android project structure successfully created!"
